# Generated by Django 5.1.4 on 2025-01-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=50)),
                ('datatype', models.CharField(max_length=50)),
                ('isActive', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_attribute',
            },
        ),
    ]
