# Generated by Django 5.1.4 on 2025-01-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0002_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiativeName', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('startDate', models.DateTimeField(max_length=25)),
                ('version', models.IntegerField(max_length=30)),
            ],
            options={
                'db_table': 'sos_initiative',
            },
        ),
    ]
