# Generated by Django 5.1.4 on 2025-01-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0003_initiative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='startDate',
            field=models.DateField(max_length=25),
        ),
    ]
