# Generated by Django 5.1.4 on 2025-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0004_alter_initiative_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('userName', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('birthDate', models.DateField(max_length=30)),
                ('contactNumber', models.IntegerField(max_length=15)),
            ],
            options={
                'db_table': 'sos_employee',
            },
        ),
    ]
