# Generated by Django 5.1.4 on 2025-01-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0005_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contactNumber',
            field=models.CharField(default='', max_length=15),
        ),
    ]
