# Generated by Django 5.1.4 on 2025-01-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0006_alter_employee_contactnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('appointmentDate', models.DateField(max_length=40)),
                ('phone', models.CharField(default='', max_length=15)),
                ('illness', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='initiative',
            name='version',
            field=models.IntegerField(),
        ),
    ]
