# Generated by Django 5.1.4 on 2025-01-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0007_client_alter_initiative_version'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='sos_Client',
        ),
    ]
