# Generated by Django 5.1.4 on 2025-01-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0008_alter_client_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('birthDate', models.DateField(max_length=20)),
                ('phone', models.CharField(default='', max_length=15)),
                ('specialization', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_Physician',
            },
        ),
    ]
