# Generated by Django 5.1.4 on 2025-02-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0010_medication_alter_physician_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow_Up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=30)),
                ('physician', models.CharField(max_length=30)),
                ('appointmentDate', models.DateField(max_length=15)),
                ('charges', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_Follow_Up',
            },
        ),
    ]
