# Generated by Django 5.1.4 on 2025-02-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0011_follow_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('joiningDate', models.DateField(max_length=15)),
                ('division', models.CharField(max_length=30)),
                ('previousEmployer', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_Staff_Member',
            },
        ),
    ]
