# Generated by Django 5.1.4 on 2025-02-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0012_staff_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('openingDate', models.DateField(max_length=12)),
                ('requiredExperience', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'sos_Position',
            },
        ),
    ]
